apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-toleration-nodeselector
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template: 
    metadata:
      labels:
        app: nginx
    spec:
    # accompanying tolerations for our node taint
      tolerations:
      - key: dedicated
        operator: Equal
        value: advanced
        effect: NoSchedule
   # nodeSelector to attract pod to desired Node Pool
      nodeSelector: 
        cloud.google.com/gke-nodepool: advanced-pool
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80